In [6]:
#Import necessary packages 

import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [7]:
df = pd.read_excel (r'/Users/MaeganBoosten/Thesis_Project/Final/SHAP Explanations/SHAP.xlsx')
print (df)

     SHAP duration  SHAP credit_amount  SHAP intallment_rate  \
0         0.007710            0.084993              0.032128
1        -0.008658           -0.015952              0.041949
2         0.018017           -0.018437             -0.001453
3         0.006538            0.076041             -0.026470
4         0.073784            0.107086              0.000000
..             ...                 ...                   ...
369       0.039525            0.157123             -0.036931
370      -0.020151           -0.058015              0.033914
371      -0.018984           -0.055113              0.031002
372       0.008481           -0.062411              0.041823
373      -0.026302           -0.051591             -0.086031

     SHAP residence_since  SHAP age  SHAP number_of_existcr  \
0               -0.003039  0.014519                0.005237
1                0.005709 -0.061866                0.006557
2                0.000734  0.030495               -0.003630
3               -0.001264  0.019763               -0.002279
4               -0.003750  0.021884               -0.004045
..                    ...       ...                     ...
369             -0.003444  0.016608               -0.003624
370              0.004684 -0.029487               -0.003024
371             -0.002277 -0.017121                0.004649
372              0.005955 -0.005447                0.006387
373             -0.008437  0.026171               -0.003830

     SHAP number_of_dependents  SHAP telephon  SHAP foreign  \
0                    -0.004958      -0.025194      0.007273
1                    -0.007162       0.019459      0.008539
2                    -0.007392       0.020021      0.008537
3                    -0.003295       0.011174      0.007289
4                    -0.005829       0.017731      0.008792
..                         ...            ...           ...
369                   0.031326       0.017253      0.007767
370                  -0.005282       0.016001      0.009345
371                  -0.005347      -0.022664      0.007853
372                   0.035664       0.019615      0.008251
373                  -0.007253       0.019624      0.008846

     SHAP account_bal_neg_bal  ...  SHAP concurrent_credits_A141  \
0                   -0.038602  ...                      0.064868
1                    0.116507  ...                     -0.014842
2                   -0.056281  ...                     -0.015520
3                    0.076674  ...                     -0.007105
4                   -0.046234  ...                     -0.013303
..                        ...  ...                           ...
369                  0.106498  ...                     -0.011968
370                  0.101309  ...                     -0.011701
371                  0.091482  ...                      0.063789
372                 -0.055730  ...                      0.084808
373                 -0.055193  ...                     -0.015361

     SHAP concurrent_credits_A142  SHAP concurrent_credits_A143  \
0                       -0.001557                      0.056772
1                       -0.001884                     -0.018032
2                       -0.001938                     -0.018546
3                        0.024076                      0.044795
4                       -0.001797                     -0.015350
..                            ...                           ...
369                     -0.001038                     -0.015620
370                     -0.000672                     -0.014204
371                      0.000652                      0.054003
372                     -0.001589                      0.072790
373                     -0.002252                     -0.017984

     SHAP type_of_housing_A151  SHAP type_of_housing_A152  \
0                    -0.004865                  -0.003527
1                    -0.006233                   0.012378
2                     0.028367                   0.012533
3                    -0.003348                  -0.004745
4                    -0.005977                  -0.004934
..                         ...                        ...
369                  -0.006660                  -0.004817
370                  -0.005147                  -0.004788
371                  -0.003713                  -0.002757
372                  -0.006283                  -0.004776
373                   0.027776                   0.012132

     SHAP type_of_housing_A153  SHAP job_highly_skilled  SHAP job_skilled  \
0                     0.002281                 0.027455          0.002194
1                    -0.013266                -0.005748         -0.001417
2                     0.001546                -0.006234         -0.001911
3                     0.000936                -0.003342          0.003468
4                     0.001117                -0.005031         -0.001292
..                         ...                      ...               ...
369                   0.001314                -0.005072         -0.000762
370                   0.002182                -0.003584         -0.002065
371                   0.001086                -0.003312         -0.001956
372                   0.001733                -0.006629         -0.001228
373                   0.001857                -0.005823         -0.001917

     SHAP job_unskilled  False Positive
0              0.002499               1
1              0.005542               0
2              0.005920               0
3             -0.010243               1
4              0.005682               0
..                  ...             ...
369            0.004899               0
370            0.004997               0
371            0.003175               0
372            0.005678               0
373            0.005488               0

[374 rows x 58 columns]

In [29]:
df1 = df[df['False Positive'] > 0]
df2 = df[df['False Positive'] < 1]

In [33]:
df1[['SHAP account_bal_no_acc', 'SHAP account_bal_neg_bal', 'SHAP credit_amount']].describe()

       SHAP account_bal_no_acc  SHAP account_bal_neg_bal  SHAP credit_amount
count               104.000000                104.000000          104.000000
mean                  0.049406                  0.021144            0.009752
std                   0.054210                  0.079660            0.081033
min                  -0.148578                 -0.059089           -0.088078
25%                   0.063371                 -0.053448           -0.048466
50%                   0.065992                 -0.038363           -0.013718
75%                   0.067081                  0.109999            0.041549
max                   0.068994                  0.117315            0.344202

In [34]:
df1.describe()

,SHAP duration,SHAP credit_amount,SHAP intallment_rate,SHAP residence_since,SHAP age,SHAP number_of_existcr,SHAP number_of_dependents,SHAP telephon,SHAP foreign,SHAP account_bal_neg_bal,...,SHAP concurrent_credits_A141,SHAP concurrent_credits_A142,SHAP concurrent_credits_A143,SHAP type_of_housing_A151,SHAP type_of_housing_A152,SHAP type_of_housing_A153,SHAP job_highly_skilled,SHAP job_skilled,SHAP job_unskilled,False Positive
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,...,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.0
mean,0.000960,0.009752,0.001746,-0.000625,0.003673,-0.001170,0.001369,-0.001493,0.005908,0.021144,...,0.006651,0.001073,0.008455,0.000531,-0.000144,0.000390,0.001824,0.000297,-0.000412,1.0
std,0.033909,0.081033,0.044430,0.004997,0.023244,0.004804,0.016107,0.023602,0.026236,0.079660,...,0.037923,0.010124,0.038245,0.012707,0.007323,0.003599,0.014715,0.002183,0.009733,0.0
min,-0.045180,-0.088078,-0.088851,-0.009491,-0.083653,-0.004865,-0.007526,-0.033769,-0.258967,-0.059089,...,-0.016249,-0.002860,-0.019405,-0.007185,-0.005944,-0.013186,-0.006729,-0.002376,-0.019022,1.0
25%,-0.025767,-0.048466,-0.038470,-0.004061,-0.005444,-0.003771,-0.007049,-0.027766,0.008233,-0.053448,...,-0.015003,-0.002079,-0.018098,-0.006163,-0.005066,0.001212,-0.005812,-0.001721,-0.010520,1.0
50%,-0.007883,-0.013718,0.032589,0.000000,0.010803,-0.003462,-0.006359,0.016813,0.008601,-0.038363,...,-0.013651,-0.001732,-0.015905,-0.005609,-0.004615,0.001541,-0.005320,-0.001202,0.005166,1.0
75%,0.009218,0.041549,0.040899,0.004899,0.020821,-0.002277,-0.005068,0.019280,0.008879,0.109999,...,-0.007197,-0.001447,0.057025,-0.003808,0.009683,0.001757,-0.004397,0.002645,0.005653,1.0
max,0.108460,0.344202,0.042552,0.006000,0.033333,0.016871,0.036110,0.020275,0.010750,0.117315,...,0.085056,0.040297,0.073760,0.028880,0.012982,0.002541,0.036727,0.003805,0.006197,1.0

In [12]:
# import libraries for visualizations

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (-1, 0)
matplotlib.rcParams['figure.facecolor'] = '#00000000'